Algoritmo "Exercício 2"

//Faça um programa que receba dois números, calcule e mostre a divisão
//do primeiro pelo segundo. Sabe-se que o segundo número não pode ser
//zero, portanto, não é necessário se preocupar com isso neste exercício.

Var
n1,n2: inteiro




Inicio
escreval ("Digite o primeiro numero: ")
leia (n1)
escreval ("Digite o segundo numero: ")
leia (n2)
escreval ("A soma entre ",n1, " e ", n2, " é :", n1+n2)
escreval ("A divisão entre ", n1, " e ", n2," é: ", n1/n2)


Fimalgoritmo